/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gilbertosantos;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

class LibraryTest {
  @Test
  void testSomeLibraryMethod() {
    final Code classUnderTest = new Code();
    assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
  }
}
